### ISSUE TITLE
Crashing on  1.21.0.76 NeoForge beta

### ISSUE THREAD

**Issue by IvoryMonkey** [lieonlion/More-Bookshelf-Variants#2]
just downloaded Neoforge 1.21.0.76 beta and MBV no longer works

**Comment by IvoryMonkey** [comment]
*in Creative inventory have not tested survival

**Comment by lieonlion** [comment]
I have found the issue, will be releasing an update within 24 hrs

**Comment by lieonlion** [comment]
should be fixed now!
